print('We are doing practice for git and it is a version control tool')
print("statement1: we are commit some changes with my email_id")
print("we are going to update the file on git editor")
print("We are going to pull the changes from remote to local branch")
print("We are made the changes in this file only for the push command")
print("we are added this comment only for newly created branch")
